name: CI
on:
  push:
    branches: [ "stable" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Test
        id: test
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CONTENT<<$EOF" >> "$GITHUB_ENV"
          echo "TEST=1" >> "$GITHUB_ENV"
          echo "TEST2=2" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"

      - name: Test
        env:
          CONTENT: ${{ steps.test.outputs.CONTENT }}
        run: echo $CONTENT

      - name: Test
        run: echo ${{ toJSON(steps.test.outputs.CONTENT) }}

      - name: Test
        run: >
          echo ${{ steps.test.outputs.CONTENT }}

      - name: Test
        run: |
          echo ${{ toJSON(github) }}

